services:

  server:
    cap_add:
      - NET_ADMIN
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server
    hostname: server
    command: ["python3", "-m", "http.server", "5000"]
    networks:
      project-net:
        ipv4_address: 172.20.0.3

  client1: 
    cap_add:
      - NET_ADMIN
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: client1
    hostname: client1
    command: ["sleep", "infinity"]
    networks:
        project-net:
          ipv4_address: 172.20.0.2

  client2:
    cap_add:
      - NET_ADMIN
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: client2
    hostname: client2
    command: ["sleep", "infinity"]
    networks:
      project-net:
        ipv4_address: 172.20.0.4


  network-controller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: network-controller
    hostname: network-controller
    privileged: true
    network_mode: host
    command: ["sleep", "infinity"]


networks:
  project-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

